export const jobs = [
  {
    id: 1,
    title: 'Senior Front-End Engineer',
    company: 'Barghchi',
    location: 'Tehran, Iran',
    url: 'https://barghchi.com/',
    description: [
      'Led the frontend architecture and development of a high-traffic e-commerce platform serving 15,000+ daily users using Next.js, TypeScript, and React Query.',
      'Led migration from WooCommerce to a modern Laravel + Next.js architecture, ensuring zero SEO loss through structured redirects, sitemap management, and URL strategy.',
      'Collaborated with designers and backend engineers to deliver a scalable and maintainable frontend system aligned with product requirements.',
      'Built a performance-optimized UI with focus on Core Web Vitals, responsive design, and SEO best practices, improving overall site performance and stability.',
      'Defined and improved frontend development workflows, ensuring code quality, consistency, and scalable component architecture across the team.',
    ],
    date: 'December 2021 – Present',
    skils: [
      'Next.js',
      'React',
      'TypeScript',
      'React Query',
      'Tailwind CSS',
      'SEO',
      'Frontend Architecture',
    ],
  },

  {
    id: 2,
    title: 'Front-End Engineer | Real-Time Systems',
    company: 'DastyarTech',
    location: 'Tehran, Iran',
    url: '',
    description: [
      'Designed and developed a real-time communication system using SignalR enabling messaging, media sharing, and file exchange between operators and users.',
      'Built an advanced chatbot flow builder using React Flow, allowing dynamic multi-step conversation design with conditional logic and form automation.',
      'Architected scalable frontend modules from scratch, focusing on performance, maintainability, and high-concurrency usage scenarios.',
      'Optimized data fetching and caching strategies using React Query, reducing unnecessary server load and improving responsiveness.',
      'Worked closely with backend and product teams to translate complex workflows into scalable UI architecture.',
    ],
    date: 'Nov 2024 – Jan 2026',
    skils: [
      'Next.js',
      'React',
      'React Query',
      'SignalR',
      'Material UI',
      'Real-time Systems',
    ],
  },

  {
    id: 3,
    title: 'Front-End Engineer | Web3 / DeFi',
    company: 'MHS Group',
    location: 'Remote',
    url: '',
    description: [
      'Developed a decentralized exchange (DEX) using Next.js, TypeScript, Ethers.js, and Wagmi, integrated with Ethereum Mainnet and Sepolia testnet.',
      'Built a Swap interface using Uniswap liquidity pools with focus on gas efficiency and transaction reliability.',
      'Implemented trading system supporting market and limit orders using custom smart contracts.',
      'Integrated blockchain event listeners and real-time transaction tracking for accurate UI state synchronization.',
      'Delivered an end-to-end Web3 trading experience with emphasis on usability, performance, and reliability.',
    ],
    date: 'Mar 2024 – Dec 2024',
    skils: [
      'Next.js',
      'TypeScript',
      'Ethers.js',
      'Wagmi',
      'Smart Contracts',
      'Web3',
    ],
  },

  {
    id: 4,
    title: 'WordPress Developer (Early Career)',
    company: 'Various Clients',
    location: 'Iran',
    url: '',
    description: [
      'Developed custom WordPress themes for e-commerce, educational, and magazine platforms with focus on performance and SEO.',
      'Built custom post types, advanced search systems, and API integrations for dynamic content-driven websites.',
      'Worked with REST APIs and CRM integrations to improve data flow between external systems and WordPress.',
      'Improved website performance and SEO through lightweight architecture and removal of page builders.',
    ],
    date: '2017 – 2021',
    skils: [
      'PHP',
      'WordPress',
      'JavaScript',
      'REST API',
      'Theme Development',
      'SEO',
    ],
  },
];
