export const projects = [
  {
    id: 1,
    title: 'AI Interview Simulator',
    company: 'Personal Project',
    location: 'Remote',
    date: '2026',
    url: 'https://ai-interview-simulator-snowy.vercel.app/',
    github: 'https://github.com/salumep/ai-interview-simulator',
    description: [
      'Built an AI-powered interview simulation platform using Next.js and Supabase.',
      'Designed relational database models and implemented Row Level Security (RLS) for secure data access.',
      'Integrated authentication and session management using Supabase Auth.',
      'Developed interview workflow management and AI-driven feedback generation features.',
      'Deployed a production-ready prototype with full authentication, database integration, and responsive UI.',
    ],
    skils: [
      'Next.js',
      'TypeScript',
      'React',
      'Supabase',
      'PostgreSQL',
      'Authentication',
      'RLS',
      'AI',
    ],
    img: {
      id: 1,
      alt: 'AI Interview Simulator',
      src: '/images/ai-interview-simulator.png',
    },
  },
  {
    id: 1,
    title: 'chromatplus',
    company: 'chromat',
    location: 'Tehran, Iran',
    date: '2023',
    url: 'http://chromatplus.ir',
    description: [
      'Optimized WordPress API for seamless integration with Next.js, enhancing content management and overall website dynamism',
    ],
    skils: [
      'Typescript',
      'Javascript',
      'React',
      'NextJs',
      'HTML & CSS',
      'wordpress',
      'PHP',
      'Docker',
      'CI/CD',
    ],
    img: {
      id: 1,
      alt: 'chromatplus project',
      src: '/images/chromatplus.png',
    },
  },
  {
    id: 2,
    title: 'Quera Blog',
    company: 'Quera',
    date: '2020',
    location: 'Tehran, Iran',
    url: 'https://quera.org/blog',
    description: [
      ' Crafted a custom-built WordPress theme for a magazine platform, featuring separate sections for employers and developers with unique dark and light modes.',
      'The customized search function resulted in an improvement in efficiently finding relevant articles within each mode.',
    ],

    skils: [
      'Javascript',
      'jQuery',
      'Theme Development',
      'HTML & CSS',
      'wordpress',
      'PHP',
    ],
    img: {
      id: 1,
      alt: 'Quera Blog',
      src: '/images/quera.png',
    },
  },
];
