import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NextThemes } from './_providers/NextThemes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} dark:text-white text-slate-700 dark:bg-[#131c30] bg-white `}
      >
        <NextThemes>{children}</NextThemes>
      </body>
    </html>
  );
}
